version: "3.9"

services:
  web:
    image: ghcr.io/bi-team-bk/bi_hub
    
    ports:
      - "$PORT:8000"
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_USER=$DATABASE_USER
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_HOST=$DATABASE_HOST
      - ALLOWED_HOSTS=$ALLOWED_HOSTS

    restart: always
